/**
 * Helper function to get the correct image path for next-image-export-optimizer
 * The optimizer generates images in the format: {filename}-opt-{size}.webp
 * For static export, we need to reference the original path and let ExportedImage handle the mapping
 */

export function getImagePath(imagePath: string): string {
  // Ensure the path starts with /
  if (!imagePath.startsWith('/')) {
    return '/' + imagePath;
  }
  return imagePath;
}

/**
 * List of common image dimensions for serving the right size
 */
export const IMAGE_SIZES = {
  thumb: 128,
  small: 384,
  medium: 640,
  large: 1080,
  xlarge: 1920,
};

/**
 * Get blur placeholder image (generated by optimizer if enabled)
 */
export function getBlurDataUrl(imagePath: string): string | undefined {
  // This would typically come from the generated metadata
  // For now, return undefined to let it load naturally
  return undefined;
}
